CREATE TABLE THEATER( 
    THEATER_ID INT NOT NULL AUTO_INCREMENT,
    Phone_Number VARCHAR(15),
    Zip_code VARCHAR(5),
    Address VARCHAR(255),
    City VARCHAR(30), 
    Opening_time DATETIME(DEFAULT)
);
