# Generated by Django 2.1.7 on 2020-03-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theater_ID', models.IntegerField(max_length=50)),
                ('Name', models.CharField(max_length=200)),
                ('Zip_code', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('City', models.TextField()),
            ],
        ),
    ]
