# Generated by Django 2.1.7 on 2020-03-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='Theater_ID',
        ),
    ]
